# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/' # Location of package file
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    # Ignore jsdom updates - vitest 4.0.6 still uses jsdom v26.1.0
    # Testing doesn't work with jsdom v27.1.0
    # Keep at v26.x until vitest supports jsdom v27.x
    # https://github.com/vitest-dev/vitest/blob/main/packages/vitest/package.json#L217
    ignore:
      - dependency-name: 'jsdom'
