name: BrowserStack Yarn

on:
  push:
    branches:
      - dev
  pull_request_target:
    types: [opened, synchronize, reopened]

env:
  CI: true
  HUSKY: 0

jobs:
  run:
    name: BrowserStack Yarn
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: "BrowserStack Env Setup"
        uses: "browserstack/github-actions/setup-env@master"
        with:
          username: ${{secrets.BROWSERSTACK_USERNAME}}
          access-key: ${{secrets.BROWSERSTACK_ACCESS_KEY}}
          build-name: "BUILD_INFO"
          project-name: "REPO_NAME"

      - name: "Start BrowserStackLocal Tunnel"
        uses: "browserstack/github-actions/setup-local@master"
        with:
          local-testing: "start"
          local-logging-level: "all-logs"
          local-identifier: "random"

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Test iOS on BrowserStack
        run: yarn test:ios

      - name: "Stop BrowserStackLocal"
        uses: "browserstack/github-actions/setup-local@master"
        with:
          local-testing: "stop"
